[package]
name = "lsr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2"
atty = "0.2"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
users = "0.11"
